---
title: "How to work with VisuNet?"
output:
    html_document:
      css: style.css
---

***

### Input format
 
***


VisuNet is available for any rule-based classifier in supported data frame formats.

#### 'Line by line' format

Data frame contains 
Required columns are:

* FEATURES
* DECISION
* ACC_RHS
* SUPP_RHS

A p-value ('PVAL') calumn is not obligatory.

```{r, echo = FALSE, warning=FALSE, message=FALSE, results='asis'}
library(VisuNet)
library(knitr)
library("kableExtra")
kable(autcon_ruleset[1:3,], format="html")%>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```


```{r, echo = TRUE, fig.align='center', warning=FALSE, eval=FALSE}
rules = (read.csv2('LbL.txt', sep='\t', header = FALSE, col.names = c('FEATURES', 'DECISION', 'ACC_RHS', 'SUPP_RHS'),stringsAsFactors=FALSE))
rules$ACC_RHS = as.numeric(rules$ACC_RHS)
rules$SUPP_RHS = as.numeric(rules$SUPP_RHS)

vis_out = visunet(rules, 'L')
```

#### R.ROSETTA output

#### RGUI ROSETTA output



### Quick run

***

### The interface

***

### Rule network customization